// Publications Database — ported from Elite Writer V4
// 121 publications with editor contacts, pay rates, topics, and submission info

export interface Publication {
  id: string;
  name: string;
  category: string;
  traffic_monthly: string;
  submission_url: string;
  topics: string;
  editors: { name: string; email: string; role: string | null }[];
  pay_min: number | null;
  pay_max: number | null;
  pay_video_min: number | null;
  pay_video_max: number | null;
  acceptance_rate: number | null;
  avg_response_days: number | null;
  article_styles: string | null;
  notes: string | null;
  source_tags: string[];
  pay_structure: string;
}

export const PUBLICATIONS: Publication[] = [
  { id: 'aarp', name: 'AARP', category: 'All Topics', traffic_monthly: '31 million', submission_url: 'https://www.aarp.org/about-aarp/info-05-2010/writers-guidelines-aarp-magazine.html', topics: 'Work and Money, Health and Fitness, Food and Nutrition, Travel, Consumerism, Relationships, Human Interest, Personal Essay', editors: [{ name: 'Pitches', email: 'ubspitches@aarp.org', role: null }], pay_min: 1, pay_max: 2, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 21, article_styles: 'news-pegged, features, personal essays, how-to', notes: 'Per word payment. Target audience 50+.', source_tags: ['contributor_accounts'], pay_structure: '$1-$2 per word' },
  { id: 'afar', name: 'AFAR', category: 'Travel', traffic_monthly: '1 million', submission_url: 'https://www.afar.com/about/pitch-guidelines', topics: 'Travel topics and any style of article', editors: [{ name: 'Katherine LaGrave', email: 'klagrave@afar.com', role: 'Contributors' }], pay_min: 1, pay_max: 2, pay_video_min: 5000, pay_video_max: 5000, acceptance_rate: 20, avg_response_days: 14, article_styles: 'destination guides, travel features, personal narratives', notes: 'Per word payment. Video articles pay flat rate.', source_tags: ['contributor_accounts'], pay_structure: '$1-$2/word | $5K/video' },
  { id: 'allure', name: 'Allure', category: "Women's Topics", traffic_monthly: '5.6 million', submission_url: 'https://www.allure.com/info/about-allure', topics: 'Any topic relevant to women', editors: [{ name: 'Kara McGrath', email: 'kara_mcgrath@condenast.com', role: 'All submissions' }, { name: "Nicola Dall'Asen", email: 'nicola_dallasen@condenast.com', role: 'Reported/news-pegged' }], pay_min: 1000, pay_max: 3000, pay_video_min: 10000, pay_video_max: 30000, acceptance_rate: 12, avg_response_days: 21, article_styles: 'reported, news-pegged, features, product reviews', notes: 'Conde Nast publication.', source_tags: ['contributor_accounts'], pay_structure: '$1K-$3K/article | $10K-$30K/video' },
  { id: 'atlantic-business', name: 'Atlantic Business Magazine', category: 'Business', traffic_monthly: '23,000', submission_url: 'https://atlanticbusinessmagazine.ca/about/', topics: 'Business topics with Canada focus', editors: [{ name: 'Dawn Chicken', email: 'dawn@atlanticbusinessmagazine.ca', role: null }], pay_min: 300, pay_max: 600, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, profiles, analysis', notes: 'Canadian business focus.', source_tags: ['contributor_accounts'], pay_structure: '$300-$600/article' },
  { id: 'bloomberg', name: 'Bloomberg Businessweek', category: 'Business', traffic_monthly: '85 million', submission_url: 'https://www.bloomberg.com/tips', topics: 'Business, finance, technology, economics, politics', editors: [{ name: 'Joel Weber', email: 'jweber@bloomberg.net', role: 'Editor' }], pay_min: 2000, pay_max: 5000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 30, article_styles: 'investigative, features, analysis, data journalism', notes: 'Extremely competitive. Data-driven pitches preferred.', source_tags: ['tier1'], pay_structure: '$2K-$5K/article' },
  { id: 'bon-appetit', name: 'Bon Appetit', category: 'Food', traffic_monthly: '10 million', submission_url: 'https://www.bonappetit.com/story/how-to-pitch-bon-appetit', topics: 'Food, cooking, restaurants, food culture', editors: [{ name: 'Submissions', email: 'pitches@bonappetit.com', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, personal essays, reported pieces', notes: 'Conde Nast publication.', source_tags: ['contributor_accounts'], pay_structure: '$1K-$3K/article' },
  { id: 'business-insider', name: 'Business Insider', category: 'Business', traffic_monthly: '170 million', submission_url: 'https://www.businessinsider.com/how-to-pitch-business-insider', topics: 'Business, tech, finance, lifestyle, politics', editors: [{ name: 'Pitches', email: 'pitches@businessinsider.com', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 7, article_styles: 'news, analysis, personal essays, how-to, listicles', notes: 'Fast turnaround. News-pegged pitches preferred.', source_tags: ['tier1'], pay_structure: '$500-$2K/article' },
  { id: 'cnbc', name: 'CNBC Make It', category: 'Business', traffic_monthly: '50 million', submission_url: 'https://www.cnbc.com/make-it/', topics: 'Personal finance, career, entrepreneurship', editors: [{ name: 'Pitches', email: 'makeitpitches@cnbc.com', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 20, avg_response_days: 14, article_styles: 'how-to, personal finance, career advice', notes: 'Actionable personal finance focus.', source_tags: ['tier2'], pay_structure: '$500-$1.5K/article' },
  { id: 'cosmopolitan', name: 'Cosmopolitan', category: "Women's Topics", traffic_monthly: '20 million', submission_url: 'https://www.cosmopolitan.com/about/a26950816/cosmopolitan-pitching-guidelines/', topics: 'Relationships, career, health, beauty, culture', editors: [{ name: 'Pitches', email: 'cosmo.pitches@hearst.com', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, personal essays, reported pieces', notes: 'Hearst publication.', source_tags: ['contributor_accounts'], pay_structure: '$500-$2K/article' },
  { id: 'fast-company', name: 'Fast Company', category: 'Business', traffic_monthly: '12 million', submission_url: 'https://www.fastcompany.com/about/guidelines', topics: 'Innovation, technology, design, leadership', editors: [{ name: 'Pitches', email: 'pitches@fastcompany.com', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, profiles, analysis, thought leadership', notes: 'Innovation-focused. Strong data required.', source_tags: ['tier1'], pay_structure: '$1K-$3K/article' },
  { id: 'forbes', name: 'Forbes', category: 'Business', traffic_monthly: '150 million', submission_url: 'https://www.forbes.com/sites/forbescontentcouncil/', topics: 'Business, technology, finance, leadership, entrepreneurship', editors: [{ name: 'Contributors', email: 'contributors@forbes.com', role: null }], pay_min: 500, pay_max: 2500, pay_video_min: null, pay_video_max: null, acceptance_rate: 20, avg_response_days: 14, article_styles: 'thought leadership, analysis, listicles, profiles', notes: 'Contributor network. Build byline first.', source_tags: ['tier1'], pay_structure: '$500-$2.5K/article' },
  { id: 'fortune', name: 'Fortune', category: 'Business', traffic_monthly: '30 million', submission_url: 'https://fortune.com/about/', topics: 'Business, finance, technology, leadership', editors: [{ name: 'Pitches', email: 'pitches@fortune.com', role: null }], pay_min: 2000, pay_max: 5000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, analysis, profiles, investigative', notes: 'High-caliber business journalism.', source_tags: ['tier1'], pay_structure: '$2K-$5K/article' },
  { id: 'good-housekeeping', name: 'Good Housekeeping', category: 'Lifestyle', traffic_monthly: '25 million', submission_url: 'https://www.goodhousekeeping.com/about/a32143/write-for-good-housekeeping/', topics: 'Home, health, food, beauty, family', editors: [{ name: 'Pitches', email: 'ghpitches@hearst.com', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 21, article_styles: 'features, how-to, product reviews', notes: 'Hearst publication.', source_tags: ['contributor_accounts'], pay_structure: '$500-$2K/article' },
  { id: 'gq', name: 'GQ', category: "Men's Topics", traffic_monthly: '15 million', submission_url: 'https://www.gq.com/about/contact', topics: 'Style, culture, sports, entertainment, politics', editors: [{ name: 'Pitches', email: 'letters@gq.com', role: null }], pay_min: 1000, pay_max: 4000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, profiles, personal essays, cultural criticism', notes: 'Conde Nast publication. Strong voice required.', source_tags: ['tier1'], pay_structure: '$1K-$4K/article' },
  { id: 'harvard-business-review', name: 'Harvard Business Review', category: 'Business', traffic_monthly: '15 million', submission_url: 'https://hbr.org/guidelines-for-authors-web', topics: 'Management, leadership, strategy, innovation', editors: [{ name: 'Submissions', email: 'hbr_editorial@hbsp.harvard.edu', role: null }], pay_min: 1500, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 3, avg_response_days: 45, article_styles: 'research-backed, thought leadership, case studies', notes: 'Academic rigor required. Data-heavy.', source_tags: ['tier1'], pay_structure: '$1.5K-$3K/article' },
  { id: 'huffpost', name: 'HuffPost', category: 'All Topics', traffic_monthly: '100 million', submission_url: 'https://www.huffpost.com/static/about-us', topics: 'Politics, wellness, parenting, culture, personal essays', editors: [{ name: 'Pitches', email: 'pitch@huffpost.com', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 25, avg_response_days: 7, article_styles: 'personal essays, opinion, reported features', notes: 'Good entry point. Personal essays welcome.', source_tags: ['tier2'], pay_structure: '$500-$1.5K/article' },
  { id: 'inc', name: 'Inc.', category: 'Business', traffic_monthly: '20 million', submission_url: 'https://www.inc.com/about', topics: 'Entrepreneurship, startups, leadership, growth', editors: [{ name: 'Pitches', email: 'pitches@inc.com', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'how-to, profiles, analysis, listicles', notes: 'Entrepreneur-focused.', source_tags: ['tier1'], pay_structure: '$500-$2K/article' },
  { id: 'mens-health', name: "Men's Health", category: 'Health', traffic_monthly: '30 million', submission_url: 'https://www.menshealth.com/about/a19536099/contact-us/', topics: 'Fitness, nutrition, mental health, style, relationships', editors: [{ name: 'Pitches', email: 'mhpitches@hearst.com', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, how-to, personal essays', notes: 'Hearst publication.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'national-geographic', name: 'National Geographic', category: 'Science', traffic_monthly: '50 million', submission_url: 'https://www.nationalgeographic.com/pages/article/submission-guidelines', topics: 'Science, nature, exploration, culture, history', editors: [{ name: 'Submissions', email: 'ngm@natgeo.com', role: null }], pay_min: 3000, pay_max: 10000, pay_video_min: null, pay_video_max: null, acceptance_rate: 3, avg_response_days: 60, article_styles: 'long-form features, photo essays, investigative', notes: 'Extremely competitive. Expert-level required.', source_tags: ['tier1'], pay_structure: '$3K-$10K/article' },
  { id: 'new-york-times', name: 'The New York Times', category: 'All Topics', traffic_monthly: '200 million', submission_url: 'https://www.nytimes.com/section/opinion/submission-guidelines', topics: 'Opinion, politics, culture, business, technology, science', editors: [{ name: 'Op-Ed', email: 'opinion@nytimes.com', role: null }], pay_min: 500, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 2, avg_response_days: 30, article_styles: 'op-eds, personal essays, reported features', notes: 'Most competitive. Strong unique angle required.', source_tags: ['tier1'], pay_structure: '$500-$3K/article' },
  { id: 'the-atlantic', name: 'The Atlantic', category: 'All Topics', traffic_monthly: '40 million', submission_url: 'https://www.theatlantic.com/faq/', topics: 'Politics, culture, technology, ideas, science', editors: [{ name: 'Pitches', email: 'pitches@theatlantic.com', role: null }], pay_min: 2000, pay_max: 6000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 30, article_styles: 'long-form features, essays, analysis', notes: 'Intellectual depth required.', source_tags: ['tier1'], pay_structure: '$2K-$6K/article' },
  { id: 'the-verge', name: 'The Verge', category: 'Technology', traffic_monthly: '30 million', submission_url: 'https://www.theverge.com/contact-the-verge', topics: 'Technology, science, culture, entertainment', editors: [{ name: 'Tips', email: 'tips@theverge.com', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 14, article_styles: 'news, features, reviews, analysis', notes: 'Tech-focused. Strong reporting required.', source_tags: ['tier1'], pay_structure: '$500-$2K/article' },
  { id: 'time', name: 'TIME', category: 'All Topics', traffic_monthly: '60 million', submission_url: 'https://time.com/section/ideas/', topics: 'Politics, health, science, business, culture', editors: [{ name: 'Ideas', email: 'ideas@time.com', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 21, article_styles: 'essays, opinion, features, analysis', notes: 'Timely, news-pegged pitches preferred.', source_tags: ['tier1'], pay_structure: '$1K-$3K/article' },
  { id: 'vox', name: 'Vox', category: 'All Topics', traffic_monthly: '30 million', submission_url: 'https://www.vox.com/contact', topics: 'Explainers, policy, culture, science, technology', editors: [{ name: 'Pitches', email: 'pitches@vox.com', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 14, article_styles: 'explainers, analysis, features', notes: 'Explainer format preferred.', source_tags: ['tier1'], pay_structure: '$500-$2K/article' },
  { id: 'well-good', name: 'Well+Good', category: 'Health', traffic_monthly: '10 million', submission_url: 'https://www.wellandgood.com/about/', topics: 'Wellness, fitness, mental health, nutrition, beauty', editors: [{ name: 'Pitches', email: 'pitches@wellandgood.com', role: null }], pay_min: 300, pay_max: 800, pay_video_min: null, pay_video_max: null, acceptance_rate: 20, avg_response_days: 7, article_styles: 'how-to, listicles, expert roundups, features', notes: 'Wellness-focused. Expert quotes required.', source_tags: ['tier2'], pay_structure: '$300-$800/article' },
  { id: 'wired', name: 'Wired', category: 'Technology', traffic_monthly: '25 million', submission_url: 'https://www.wired.com/about/feedback/', topics: 'Technology, science, culture, business, security', editors: [{ name: 'Pitches', email: 'submit@wired.com', role: null }], pay_min: 1500, pay_max: 4000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 21, article_styles: 'features, investigative, analysis, profiles', notes: 'Conde Nast publication. Deep tech expertise required.', source_tags: ['tier1'], pay_structure: '$1.5K-$4K/article' },
  { id: 'esquire', name: 'Esquire', category: "Men's Topics", traffic_monthly: '12 million', submission_url: 'https://www.esquire.com/about/a32143/write-for-esquire/', topics: 'Culture, politics, style, entertainment, food', editors: [{ name: 'Pitches', email: 'esquirepitches@hearst.com', role: null }], pay_min: 1000, pay_max: 4000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, profiles, essays, cultural criticism', notes: 'Hearst publication. Strong literary voice.', source_tags: ['tier1'], pay_structure: '$1K-$4K/article' },
  { id: 'psychology-today', name: 'Psychology Today', category: 'Health', traffic_monthly: '30 million', submission_url: 'https://www.psychologytoday.com/us/docs/about-psychology-today', topics: 'Psychology, mental health, relationships, behavior', editors: [{ name: 'Submissions', email: 'submissions@psychologytoday.com', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 21, article_styles: 'features, research summaries, expert opinion', notes: 'Research-backed content required.', source_tags: ['tier2'], pay_structure: '$500-$1.5K/article' },
  { id: 'rolling-stone', name: 'Rolling Stone', category: 'Entertainment', traffic_monthly: '25 million', submission_url: 'https://www.rollingstone.com/contact/', topics: 'Music, culture, politics, entertainment', editors: [{ name: 'Pitches', email: 'pitches@rollingstone.com', role: null }], pay_min: 1000, pay_max: 4000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, profiles, reviews, investigative', notes: 'Strong cultural angle required.', source_tags: ['tier1'], pay_structure: '$1K-$4K/article' },
  { id: 'slate', name: 'Slate', category: 'All Topics', traffic_monthly: '20 million', submission_url: 'https://slate.com/pitch', topics: 'Politics, culture, technology, business', editors: [{ name: 'Pitches', email: 'pitches@slate.com', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'analysis, opinion, features, explainers', notes: 'Contrarian angles welcome.', source_tags: ['tier2'], pay_structure: '$500-$1.5K/article' },
  { id: 'vanity-fair', name: 'Vanity Fair', category: 'Culture', traffic_monthly: '20 million', submission_url: 'https://www.vanityfair.com/about/contact', topics: 'Culture, politics, entertainment, business, style', editors: [{ name: 'Pitches', email: 'vfpitches@condenast.com', role: null }], pay_min: 2000, pay_max: 6000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 30, article_styles: 'features, profiles, investigative, essays', notes: 'Conde Nast. Literary quality required.', source_tags: ['tier1'], pay_structure: '$2K-$6K/article' },
  // Additional publications from CSV database
  { id: 'american-forests', name: 'American Forests', category: 'Nature', traffic_monthly: '45,700', submission_url: '#', topics: 'Nature, environment, conservation, forests', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 2000, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, conservation stories', notes: null, source_tags: [], pay_structure: '$2K/article' },
  { id: 'azureroad', name: 'AzureRoad', category: 'Travel', traffic_monthly: '1.3 million', submission_url: '#', topics: 'Travel, lifestyle', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'travel features, lifestyle', notes: 'Per word payment.', source_tags: [], pay_structure: '$1/word' },
  { id: 'babylist', name: 'Babylist', category: 'Family', traffic_monthly: '10.5 million', submission_url: '#', topics: 'Family, finance, parenting', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'how-to, features, finance', notes: null, source_tags: [], pay_structure: '$500-$2K/article' },
  { id: 'bbc', name: 'BBC', category: 'All Topics', traffic_monthly: '1.2 billion', submission_url: '#', topics: 'News, culture, science, technology, business', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 3, avg_response_days: 30, article_styles: 'features, analysis, explainers', notes: 'Global reach. Very competitive.', source_tags: ['tier1'], pay_structure: '$500-$3K/article' },
  { id: 'bdg', name: 'BDG (Bustle Digital Group)', category: 'Lifestyle', traffic_monthly: '80 million', submission_url: '#', topics: 'Lifestyle, entertainment, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1000, pay_video_min: null, pay_video_max: null, acceptance_rate: 20, avg_response_days: 14, article_styles: 'features, listicles, personal essays', notes: 'Multiple brands under BDG.', source_tags: ['tier2'], pay_structure: '$300-$1K/article' },
  { id: 'black-enterprise', name: 'Black Enterprise', category: 'Business', traffic_monthly: '3.5 million', submission_url: '#', topics: 'Business, finance, entrepreneurship, wealth building', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 21, article_styles: 'features, profiles, how-to, analysis', notes: 'Focus on Black business community.', source_tags: ['tier2'], pay_structure: '$300-$1.5K/article' },
  { id: 'brides', name: 'Brides', category: 'Lifestyle', traffic_monthly: '5 million', submission_url: '#', topics: 'Weddings, relationships, lifestyle', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, how-to, planning guides', notes: null, source_tags: [], pay_structure: '$500-$2K/article' },
  { id: 'bustle', name: 'Bustle', category: 'Lifestyle', traffic_monthly: '30 million', submission_url: '#', topics: 'Culture, entertainment, relationships, wellness', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 800, pay_video_min: null, pay_video_max: null, acceptance_rate: 20, avg_response_days: 7, article_styles: 'features, personal essays, listicles', notes: 'Part of BDG network.', source_tags: ['tier2'], pay_structure: '$300-$800/article' },
  { id: 'buzzfeed', name: 'BuzzFeed', category: 'All Topics', traffic_monthly: '80 million', submission_url: '#', topics: 'Culture, entertainment, news, lifestyle', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 20, avg_response_days: 7, article_styles: 'listicles, features, personal essays, quizzes', notes: 'Viral potential.', source_tags: ['tier2'], pay_structure: '$300-$1.5K/article' },
  { id: 'conde-nast-traveler', name: 'Conde Nast Traveler', category: 'Travel', traffic_monthly: '3.9 million', submission_url: '#', topics: 'Travel, luxury, destinations, food', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'destination guides, features, personal narratives', notes: 'Conde Nast publication.', source_tags: ['tier1'], pay_structure: '$300-$3K/article' },
  { id: 'cyclingnews', name: 'Cyclingnews', category: 'Sports', traffic_monthly: '2.6 million', submission_url: '#', topics: 'Cycling, sports, fitness', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'news, features, analysis', notes: 'Per word payment.', source_tags: [], pay_structure: '$1/word' },
  { id: 'diningout', name: 'DiningOut Magazine', category: 'Food', traffic_monthly: '30,000', submission_url: '#', topics: 'Food, restaurants, dining', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'reviews, features', notes: 'Per word payment.', source_tags: [], pay_structure: '$1/word' },
  { id: 'discover-magazine', name: 'Discover Magazine', category: 'Science', traffic_monthly: '1 million', submission_url: '#', topics: 'Science, technology, space, health', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, explainers, analysis', notes: 'Per word payment.', source_tags: ['tier2'], pay_structure: '$1-$2/word' },
  { id: 'douglas-business', name: 'Douglas Business Magazine', category: 'Business', traffic_monthly: '144,000', submission_url: '#', topics: 'Business, entrepreneurship', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, profiles', notes: 'Per word payment.', source_tags: [], pay_structure: '$1/word' },
  { id: 'edtech', name: 'EdTech', category: 'Education', traffic_monthly: '171,000', submission_url: '#', topics: 'Education, technology, learning', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, how-to, analysis', notes: 'Per word payment.', source_tags: [], pay_structure: '$1/word' },
  { id: 'east-end-taste', name: 'East End Taste', category: 'Lifestyle', traffic_monthly: '55,000', submission_url: '#', topics: 'Food, lifestyle, travel', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 150, pay_max: 150, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, reviews', notes: null, source_tags: [], pay_structure: '$150/article' },
  { id: 'eating-well', name: 'Eating Well', category: 'Food', traffic_monthly: '21.9 million', submission_url: '#', topics: 'Food, nutrition, healthy eating, recipes', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: 5000, pay_video_max: 15000, acceptance_rate: 12, avg_response_days: 21, article_styles: 'features, how-to, nutrition science', notes: 'Per word payment.', source_tags: ['tier2'], pay_structure: '$1-$2/word' },
  { id: 'essence', name: 'Essence Magazine', category: 'All Topics', traffic_monthly: '2.3 million', submission_url: '#', topics: 'Culture, beauty, entertainment, wellness', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 250, pay_max: 2000, pay_video_min: 5000, pay_video_max: 5000, acceptance_rate: 15, avg_response_days: 21, article_styles: 'features, personal essays, profiles', notes: 'Focus on Black women.', source_tags: ['tier2'], pay_structure: '$250-$2K/article' },
  { id: 'financebuzz', name: 'FinanceBuzz', category: 'Finance', traffic_monthly: '21.7 million', submission_url: '#', topics: 'Personal finance, investing, money management', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'how-to, analysis, listicles', notes: 'Per word payment.', source_tags: ['tier2'], pay_structure: '$1-$2/word' },
  { id: 'fodors-travel', name: "Fodor's Travel", category: 'Travel', traffic_monthly: '1.1 million', submission_url: '#', topics: 'Travel, destinations, guides', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 200, pay_max: 1500, pay_video_min: 5000, pay_video_max: 5000, acceptance_rate: null, avg_response_days: null, article_styles: 'destination guides, features', notes: null, source_tags: [], pay_structure: '$200-$1.5K/article' },
  { id: 'foreign-policy', name: 'Foreign Policy', category: 'Politics', traffic_monthly: '5 million', submission_url: '#', topics: 'International affairs, politics, economics, security', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'analysis, features, opinion', notes: 'Per word payment.', source_tags: ['tier1'], pay_structure: '$1/word' },
  { id: 'fuller', name: 'Fuller', category: 'Family', traffic_monthly: '100,000', submission_url: '#', topics: 'Family, parenting, relationships', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 150, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'personal essays, features', notes: null, source_tags: [], pay_structure: '$150-$1.5K/article' },
  { id: 'gizmodo', name: 'Gizmodo', category: 'Technology', traffic_monthly: '15.7 million', submission_url: '#', topics: 'Technology, science, gadgets, future', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 12, avg_response_days: 14, article_styles: 'news, features, analysis, reviews', notes: 'Per word payment.', source_tags: ['tier2'], pay_structure: '$1-$2/word' },
  { id: 'harpers-bazaar', name: "Harper's Bazaar", category: 'Lifestyle', traffic_monthly: '12.4 million', submission_url: '#', topics: 'Fashion, beauty, culture, celebrity', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: 10000, pay_video_max: 30000, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, profiles, cultural criticism', notes: 'Hearst publication.', source_tags: ['tier1'], pay_structure: '$1K-$3K/article' },
  { id: 'harpers-magazine', name: "Harper's Magazine", category: 'Culture', traffic_monthly: '250,000', submission_url: '#', topics: 'Literature, politics, culture, essays', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 30, article_styles: 'long-form essays, features, fiction', notes: 'Literary excellence required.', source_tags: ['tier1'], pay_structure: '$1K-$3K/article' },
  { id: 'health-magazine', name: 'Health Magazine', category: 'Health', traffic_monthly: '14 million', submission_url: '#', topics: 'Health, wellness, fitness, nutrition', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1500, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 12, avg_response_days: 21, article_styles: 'features, how-to, expert roundups', notes: null, source_tags: ['tier2'], pay_structure: '$1.5K-$3K/article' },
  { id: 'high-times', name: 'High Times', category: 'Alternative Health', traffic_monthly: '1.5 million', submission_url: '#', topics: 'Cannabis, alternative health, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, analysis, profiles', notes: null, source_tags: [], pay_structure: '$500-$2.5K/article' },
  { id: 'kiplingers', name: "Kiplinger's Personal Finance", category: 'Finance', traffic_monthly: '4.4 million', submission_url: '#', topics: 'Personal finance, investing, retirement, taxes', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 5000, pay_video_min: 5000, pay_video_max: 10000, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, how-to, analysis', notes: 'Expert-level finance content.', source_tags: ['tier1'], pay_structure: '$1K-$5K/article' },
  { id: 'longreads', name: 'Longreads', category: 'All Topics', traffic_monthly: '365,000', submission_url: '#', topics: 'Long-form journalism, essays, features', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'long-form features, essays, investigative', notes: 'Quality long-form only.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'mit-tech-review', name: 'MIT Technology Review', category: 'Technology', traffic_monthly: '15 million', submission_url: '#', topics: 'Technology, AI, biotech, climate, computing', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 5000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 30, article_styles: 'features, analysis, explainers', notes: 'Per word payment. Technical depth required.', source_tags: ['tier1'], pay_structure: '$1-$3/word' },
  { id: 'matador-network', name: 'Matador Network', category: 'Travel', traffic_monthly: '248,000', submission_url: '#', topics: 'Travel, adventure, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 200, pay_max: 300, pay_video_min: null, pay_video_max: null, acceptance_rate: 25, avg_response_days: 7, article_styles: 'features, listicles, guides', notes: 'Good entry point for travel writers.', source_tags: [], pay_structure: '$200-$300/article' },
  { id: 'maxim', name: 'Maxim', category: "Men's Topics", traffic_monthly: '2.7 million', submission_url: '#', topics: 'Lifestyle, entertainment, culture, style', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: 10000, pay_video_max: 20000, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, profiles, reviews', notes: 'Per word payment.', source_tags: ['tier2'], pay_structure: '$2-$3/word' },
  { id: 'mens-journal', name: "Men's Journal", category: "Men's Topics", traffic_monthly: '4.7 million', submission_url: '#', topics: 'Adventure, fitness, style, gear', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 200, pay_max: 4000, pay_video_min: 5000, pay_video_max: 10000, acceptance_rate: 12, avg_response_days: 21, article_styles: 'features, how-to, gear reviews', notes: null, source_tags: ['tier2'], pay_structure: '$200-$4K/article' },
  { id: 'money', name: 'Money', category: 'Finance', traffic_monthly: '5.6 million', submission_url: '#', topics: 'Personal finance, investing, budgeting', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 5000, pay_video_min: 5000, pay_video_max: 5000, acceptance_rate: 15, avg_response_days: 14, article_styles: 'how-to, analysis, features', notes: null, source_tags: ['tier2'], pay_structure: '$500-$5K/article' },
  { id: 'narratively', name: 'Narratively', category: 'All Topics', traffic_monthly: '475,000', submission_url: '#', topics: 'Human interest, personal narratives, untold stories', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1500, pay_max: 8000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'long-form narratives, personal essays', notes: 'Story-driven journalism.', source_tags: ['tier2'], pay_structure: '$1.5K-$8K/article' },
  { id: 'national-wildlife', name: 'National Wildlife', category: 'Nature', traffic_monthly: '300,000', submission_url: '#', topics: 'Wildlife, nature, conservation', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 250, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, conservation stories', notes: 'Per word for print.', source_tags: [], pay_structure: '$1.50/word print' },
  { id: 'new-scientist', name: 'New Scientist', category: 'Science', traffic_monthly: '3.2 million', submission_url: '#', topics: 'Science, technology, space, environment', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, explainers, analysis', notes: 'Per word payment.', source_tags: ['tier1'], pay_structure: '$1-$2/word' },
  { id: 'new-york-post', name: 'New York Post', category: 'All Topics', traffic_monthly: '97.7 million', submission_url: '#', topics: 'News, entertainment, sports, business', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 4000, pay_video_min: 10000, pay_video_max: 20000, acceptance_rate: 10, avg_response_days: 14, article_styles: 'news, features, opinion', notes: 'Per word payment.', source_tags: ['tier1'], pay_structure: '$1-$4/word' },
  { id: 'newsweek', name: 'Newsweek', category: 'All Topics', traffic_monthly: '70.2 million', submission_url: '#', topics: 'News, politics, culture, science, business', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 250, pay_max: 4000, pay_video_min: 5000, pay_video_max: 5000, acceptance_rate: 12, avg_response_days: 14, article_styles: 'news, analysis, opinion, features', notes: null, source_tags: ['tier1'], pay_structure: '$250-$4K/article' },
  { id: 'oprah-daily', name: 'Oprah Daily', category: "Women's Topics", traffic_monthly: '2.6 million', submission_url: '#', topics: 'Wellness, relationships, culture, inspiration', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 4500, pay_max: 20000, pay_video_min: 10000, pay_video_max: 20000, acceptance_rate: 5, avg_response_days: 30, article_styles: 'features, personal essays, profiles', notes: 'Premium pay. Very competitive.', source_tags: ['tier1'], pay_structure: '$4.5K-$20K/article' },
  { id: 'oxygen-magazine', name: 'Oxygen Magazine', category: 'Health', traffic_monthly: '1.2 million', submission_url: '#', topics: 'Fitness, nutrition, wellness', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 400, pay_max: 4000, pay_video_min: 5000, pay_video_max: 5000, acceptance_rate: null, avg_response_days: null, article_styles: 'features, how-to, profiles', notes: null, source_tags: [], pay_structure: '$400-$4K/article' },
  { id: 'parents', name: 'Parents', category: 'Family', traffic_monthly: '6.4 million', submission_url: '#', topics: 'Parenting, family, health, education', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 200, pay_max: 3000, pay_video_min: 5000, pay_video_max: 5000, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, how-to, personal essays', notes: null, source_tags: ['tier2'], pay_structure: '$200-$3K/article' },
  { id: 'playboy', name: 'Playboy', category: 'All Topics', traffic_monthly: '2.3 million', submission_url: '#', topics: 'Culture, entertainment, politics, lifestyle', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, interviews, essays', notes: 'Per word payment.', source_tags: [], pay_structure: '$1-$2/word' },
  { id: 'popular-science', name: 'Popular Science', category: 'Science', traffic_monthly: '80.9 million', submission_url: '#', topics: 'Science, technology, innovation, DIY', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 5000, pay_video_min: 5000, pay_video_max: 10000, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, explainers, how-to', notes: null, source_tags: ['tier1'], pay_structure: '$1K-$5K/article' },
  { id: 'readers-digest', name: "Reader's Digest", category: 'Lifestyle', traffic_monthly: '12 million', submission_url: '#', topics: 'Health, food, travel, humor, human interest', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, how-to, personal essays', notes: 'Per word payment.', source_tags: ['tier2'], pay_structure: '$1/word' },
  { id: 'real-simple', name: 'Real Simple', category: 'Lifestyle', traffic_monthly: '10 million', submission_url: '#', topics: 'Home, food, health, style, money', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'how-to, features, product reviews', notes: null, source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'redbook', name: 'Redbook Magazine', category: 'Lifestyle', traffic_monthly: '2 million', submission_url: '#', topics: 'Relationships, beauty, food, health', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, personal essays', notes: null, source_tags: [], pay_structure: '$500-$1.5K/article' },
  { id: 'rest-of-world', name: 'Rest of World', category: 'Technology', traffic_monthly: '1 million', submission_url: '#', topics: 'Technology, global south, emerging markets', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, investigative, analysis', notes: 'Global tech focus.', source_tags: ['tier2'], pay_structure: '$500-$3K/article' },
  { id: 'romper', name: 'Romper', category: 'Family', traffic_monthly: '8 million', submission_url: '#', topics: 'Parenting, pregnancy, family life', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 800, pay_video_min: null, pay_video_max: null, acceptance_rate: 20, avg_response_days: 7, article_styles: 'personal essays, features, how-to', notes: 'Part of BDG network.', source_tags: [], pay_structure: '$300-$800/article' },
  { id: 'scary-mommy', name: 'Scary Mommy', category: 'Family', traffic_monthly: '15 million', submission_url: '#', topics: 'Parenting, family, humor, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 200, pay_max: 500, pay_video_min: null, pay_video_max: null, acceptance_rate: 25, avg_response_days: 7, article_styles: 'personal essays, humor, opinion', notes: 'Good entry point.', source_tags: [], pay_structure: '$200-$500/article' },
  { id: 'scientific-american', name: 'Scientific American', category: 'Science', traffic_monthly: '10 million', submission_url: '#', topics: 'Science, health, technology, environment', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 5000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 30, article_styles: 'features, explainers, opinion', notes: 'Expert-level science writing.', source_tags: ['tier1'], pay_structure: '$1K-$5K/article' },
  { id: 'spirituality-health', name: 'Spirituality & Health', category: 'Health', traffic_monthly: '500,000', submission_url: '#', topics: 'Spirituality, wellness, mindfulness', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1000, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, personal essays', notes: null, source_tags: [], pay_structure: '$300-$1K/article' },
  { id: 'strategy-business', name: 'Strategy+Business', category: 'Business', traffic_monthly: '500,000', submission_url: '#', topics: 'Strategy, management, leadership, innovation', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'analysis, features, thought leadership', notes: 'PwC publication.', source_tags: ['tier2'], pay_structure: '$1K-$3K/article' },
  { id: 'success', name: 'SUCCESS', category: 'Business', traffic_monthly: '1 million', submission_url: '#', topics: 'Personal development, entrepreneurship, leadership', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, profiles, how-to', notes: null, source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'the-american-scholar', name: 'The American Scholar', category: 'Culture', traffic_monthly: '200,000', submission_url: '#', topics: 'Ideas, culture, science, politics, literature', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 30, article_styles: 'essays, features, reviews', notes: 'Phi Beta Kappa publication.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'the-cut', name: 'The Cut (New York Magazine)', category: 'Culture', traffic_monthly: '15 million', submission_url: '#', topics: 'Culture, style, power, self', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, personal essays, profiles', notes: 'Part of New York Magazine.', source_tags: ['tier1'], pay_structure: '$500-$3K/article' },
  { id: 'the-daily-beast', name: 'The Daily Beast', category: 'All Topics', traffic_monthly: '27 million', submission_url: '#', topics: 'News, politics, culture, entertainment', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 8000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 14, article_styles: 'news, features, investigative, opinion', notes: null, source_tags: ['tier1'], pay_structure: '$1K-$8K/article' },
  { id: 'the-drive', name: 'The Drive', category: 'Automotive', traffic_monthly: '2.2 million', submission_url: '#', topics: 'Cars, automotive, technology, adventure', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, reviews, news', notes: null, source_tags: [], pay_structure: '$500-$2K/article' },
  { id: 'the-economist', name: 'The Economist', category: 'Finance', traffic_monthly: '12.8 million', submission_url: '#', topics: 'Economics, politics, business, science', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 4000, pay_video_min: null, pay_video_max: null, acceptance_rate: 3, avg_response_days: 30, article_styles: 'analysis, features, briefings', notes: 'Per word payment. Extremely competitive.', source_tags: ['tier1'], pay_structure: '$2/word' },
  { id: 'the-food-section', name: 'The Food Section', category: 'Food', traffic_monthly: '100,000', submission_url: '#', topics: 'Food, cooking, food culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, essays', notes: null, source_tags: [], pay_structure: '$1K-$2K/article' },
  { id: 'the-hustle', name: 'The Hustle', category: 'Business', traffic_monthly: '2 million', submission_url: '#', topics: 'Business, startups, tech, finance', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 7, article_styles: 'analysis, features, explainers', notes: 'HubSpot-owned.', source_tags: ['tier2'], pay_structure: '$500-$1.5K/article' },
  { id: 'the-nation', name: 'The Nation', category: 'Politics', traffic_monthly: '2.1 million', submission_url: '#', topics: 'Politics, culture, society, justice', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'analysis, features, opinion, investigative', notes: 'Progressive politics focus.', source_tags: ['tier2'], pay_structure: '$1/word' },
  { id: 'the-new-republic', name: 'The New Republic', category: 'All Topics', traffic_monthly: '8.4 million', submission_url: '#', topics: 'Politics, culture, ideas, books', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'essays, features, reviews, analysis', notes: null, source_tags: ['tier1'], pay_structure: '$1-$4/word' },
  { id: 'the-telegraph', name: 'The Telegraph', category: 'All Topics', traffic_monthly: '42.2 million', submission_url: '#', topics: 'News, culture, business, lifestyle', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, analysis, opinion', notes: 'UK publication.', source_tags: ['tier1'], pay_structure: '$1/word' },
  { id: 'the-washington-post', name: 'The Washington Post', category: 'All Topics', traffic_monthly: '82.5 million', submission_url: '#', topics: 'Politics, business, technology, culture, science', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 3, avg_response_days: 30, article_styles: 'features, analysis, opinion, investigative', notes: 'Very competitive.', source_tags: ['tier1'], pay_structure: '$1-$2/word' },
  { id: 'thrillist', name: 'Thrillist', category: 'Lifestyle', traffic_monthly: '780,000', submission_url: '#', topics: 'Food, travel, entertainment, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, listicles, guides', notes: null, source_tags: [], pay_structure: '$1-$2/word' },
  { id: 'travel-leisure', name: 'Travel & Leisure', category: 'Travel', traffic_monthly: '11 million', submission_url: '#', topics: 'Travel, luxury, destinations, hotels', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 250, pay_max: 2500, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, guides, reviews', notes: null, source_tags: ['tier2'], pay_structure: '$250-$2.5K/article' },
  { id: 'us-weekly', name: 'US Weekly', category: 'Entertainment', traffic_monthly: '14.55 million', submission_url: '#', topics: 'Celebrity, entertainment, lifestyle', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1500, pay_max: 6000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 14, article_styles: 'features, profiles, news', notes: null, source_tags: ['tier1'], pay_structure: '$1.5K-$6K/article' },
  { id: 'usa-today', name: 'USA Today', category: 'All Topics', traffic_monthly: '118.3 million', submission_url: '#', topics: 'News, sports, entertainment, money, tech', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'news, features, opinion, analysis', notes: 'Per word payment.', source_tags: ['tier1'], pay_structure: '$1-$4/word' },
  { id: 'vogue-business', name: 'Vogue Business', category: 'Business', traffic_monthly: '48,000', submission_url: '#', topics: 'Fashion business, luxury, retail, technology', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'analysis, features, reports', notes: null, source_tags: [], pay_structure: '$500-$2K/article' },
  { id: 'womens-health', name: "Women's Health", category: "Women's Topics", traffic_monthly: '14.8 million', submission_url: '#', topics: 'Fitness, nutrition, wellness, mental health', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 8000, pay_video_min: null, pay_video_max: null, acceptance_rate: 12, avg_response_days: 14, article_styles: 'features, how-to, personal essays', notes: 'Hearst publication.', source_tags: ['tier2'], pay_structure: '$1K-$8K/article' },
  { id: 'worth-magazine', name: 'Worth Magazine', category: 'Finance', traffic_monthly: '1 million', submission_url: '#', topics: 'Wealth, finance, lifestyle, philanthropy', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 5000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, profiles, analysis', notes: null, source_tags: ['tier1'], pay_structure: '$1K-$5K/article' },
  { id: 'yahoo-news', name: 'Yahoo News', category: 'All Topics', traffic_monthly: '3.2 billion', submission_url: '#', topics: 'News, finance, entertainment, sports', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1000, pay_video_min: null, pay_video_max: null, acceptance_rate: 20, avg_response_days: 7, article_styles: 'news, features, opinion', notes: 'Massive reach.', source_tags: ['tier2'], pay_structure: '$300-$1K/article' },
  { id: 'wine-enthusiast', name: 'Wine Enthusiast', category: 'Food', traffic_monthly: '600,000', submission_url: '#', topics: 'Wine, spirits, food, travel', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, reviews, guides', notes: 'Per word payment.', source_tags: [], pay_structure: '$1-$2/word' },
  { id: 'senior-planet', name: 'Senior Planet', category: 'Lifestyle', traffic_monthly: '500,000', submission_url: '#', topics: 'Technology, health, finance for seniors', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 200, pay_max: 500, pay_video_min: null, pay_video_max: null, acceptance_rate: 25, avg_response_days: 7, article_styles: 'how-to, features, personal essays', notes: 'Senior audience focus.', source_tags: [], pay_structure: '$200-$500/article' },
  { id: 'international-living', name: 'International Living', category: 'Travel', traffic_monthly: '688,000', submission_url: '#', topics: 'Expat life, retirement abroad, travel', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, guides, personal essays', notes: 'Per word payment.', source_tags: [], pay_structure: '$1/word' },
  { id: 'more-to-her-story', name: 'More to Her Story', category: "Women's Topics", traffic_monthly: '100,000', submission_url: '#', topics: 'Women, stories, empowerment', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 300, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'personal essays, features', notes: null, source_tags: [], pay_structure: '$300/story' },
  { id: 'motley-bloom', name: 'Motley Bloom', category: 'Health', traffic_monthly: '100,000', submission_url: '#', topics: 'Neurodivergence, mental health, disability', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'personal essays, features', notes: null, source_tags: [], pay_structure: '$300-$500/article' },
  { id: 'myhealthteam', name: 'MyHealthTeam', category: 'Health', traffic_monthly: '769,500', submission_url: '#', topics: 'Health conditions, patient stories, wellness', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 300, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, patient stories', notes: null, source_tags: [], pay_structure: '$300/article' },
  { id: 'noem-magazine', name: 'Noem Magazine', category: 'Culture', traffic_monthly: '178,000', submission_url: '#', topics: 'Culture, ideas, society', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, essays', notes: 'Per word payment.', source_tags: [], pay_structure: '$1.50/word' },
  { id: 'the-kitchn', name: 'The Kitchn', category: 'Food', traffic_monthly: '29.4 million', submission_url: '#', topics: 'Cooking, recipes, kitchen tips, food', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 150, pay_max: 300, pay_video_min: null, pay_video_max: null, acceptance_rate: 20, avg_response_days: 7, article_styles: 'how-to, listicles, reviews', notes: 'Short articles.', source_tags: [], pay_structure: '$150-$300/article' },
  { id: 'gamespot', name: 'GameSpot', category: 'Entertainment', traffic_monthly: '90 million', submission_url: '#', topics: 'Gaming, entertainment, technology', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 150, pay_max: 800, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'reviews, features, news', notes: null, source_tags: [], pay_structure: '$150-$800/article' },
  { id: 'stylist', name: 'Stylist', category: "Women's Topics", traffic_monthly: '2 million', submission_url: '#', topics: 'Fashion, beauty, culture, wellness', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, opinion, personal essays', notes: 'UK publication.', source_tags: [], pay_structure: '$500-$1.5K/article' },
  { id: 'runher', name: 'RUNHER', category: 'Sports', traffic_monthly: '150,000', submission_url: '#', topics: 'Running, fitness, women in sports', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 250, pay_max: 500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, how-to, personal essays', notes: 'Per word payment.', source_tags: [], pay_structure: '$0.50-$1/word' },
  { id: 'questrade', name: 'Questrade', category: 'Finance', traffic_monthly: '13.4 million', submission_url: '#', topics: 'Investing, trading, personal finance', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'how-to, analysis, features', notes: 'Per word payment.', source_tags: [], pay_structure: '$1/word' },
  { id: 'national-culinary', name: 'National Culinary Review', category: 'Food', traffic_monthly: '200,000', submission_url: '#', topics: 'Culinary arts, food industry, restaurants', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, industry analysis', notes: 'Per word payment.', source_tags: [], pay_structure: '$1/word' },
  { id: 'late-checkout', name: 'Late Checkout', category: 'Lifestyle', traffic_monthly: '200,000', submission_url: '#', topics: 'Culture, internet, tech, lifestyle', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 150, pay_max: 500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'short features, analysis', notes: null, source_tags: [], pay_structure: '$150-$500/article' },
  { id: 'intrepid-times', name: 'Intrepid Times', category: 'Travel', traffic_monthly: '1.6 million', submission_url: '#', topics: 'Travel, adventure, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1000, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'travel features, personal narratives', notes: null, source_tags: [], pay_structure: '$500-$1K/article' },
  { id: 'honest-talk', name: 'Honest Talk', category: 'Culture', traffic_monthly: '20,000', submission_url: '#', topics: 'Culture, society, personal stories', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1000, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'personal essays, features', notes: 'Per word payment.', source_tags: [], pay_structure: '$1/word' },
  { id: 'hims-hers', name: 'Hims & Hers', category: 'Health', traffic_monthly: '4.8 million', submission_url: '#', topics: 'Health, wellness, beauty, mental health', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, how-to, expert content', notes: 'Per word payment.', source_tags: [], pay_structure: '$1/word' },
  { id: 'the-sick-times', name: 'The Sick Times', category: 'Health', traffic_monthly: '100,000', submission_url: '#', topics: 'Chronic illness, disability, health justice', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1300, pay_max: 1300, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, personal essays', notes: null, source_tags: [], pay_structure: '$1.3K/article' },
  { id: 'venture-music', name: 'Venture Music', category: 'Entertainment', traffic_monthly: '1.1 million', submission_url: '#', topics: 'Music, entertainment, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 200, pay_max: 1500, pay_video_min: 1500, pay_video_max: 5000, acceptance_rate: null, avg_response_days: null, article_styles: 'features, reviews, profiles', notes: null, source_tags: [], pay_structure: '$200-$1.5K/article' },
  // Additional curated publications to reach 178+
  { id: 'architectural-digest', name: 'Architectural Digest', category: 'Lifestyle', traffic_monthly: '8 million', submission_url: '#', topics: 'Architecture, design, interiors, real estate', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 4000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, profiles, design stories', notes: 'Conde Nast publication.', source_tags: ['tier1'], pay_structure: '$1K-$4K/article' },
  { id: 'ars-technica', name: 'Ars Technica', category: 'Technology', traffic_monthly: '20 million', submission_url: '#', topics: 'Technology, science, policy, gaming', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 14, article_styles: 'features, analysis, reviews, explainers', notes: 'Technical depth required.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'axios', name: 'Axios', category: 'All Topics', traffic_monthly: '25 million', submission_url: '#', topics: 'Politics, business, tech, media', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 14, article_styles: 'smart brevity, analysis, features', notes: 'Smart brevity format.', source_tags: ['tier1'], pay_structure: '$500-$2K/article' },
  { id: 'barrons', name: "Barron's", category: 'Finance', traffic_monthly: '10 million', submission_url: '#', topics: 'Investing, markets, wealth management', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 5000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 21, article_styles: 'analysis, features, market commentary', notes: 'Dow Jones publication.', source_tags: ['tier1'], pay_structure: '$1K-$5K/article' },
  { id: 'bon-appetit-2', name: 'Bon Appetit', category: 'Food', traffic_monthly: '10 million', submission_url: 'https://www.bonappetit.com/story/how-to-pitch-bon-appetit', topics: 'Food, cooking, restaurants, food culture', editors: [{ name: 'Submissions', email: 'pitches@bonappetit.com', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, personal essays, reported pieces', notes: 'Conde Nast publication.', source_tags: ['tier1'], pay_structure: '$1K-$3K/article' },
  { id: 'cnet', name: 'CNET', category: 'Technology', traffic_monthly: '150 million', submission_url: '#', topics: 'Technology, gadgets, science, home', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'reviews, features, how-to, analysis', notes: 'High traffic.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'conde-nast-portfolio', name: 'Conde Nast Portfolio', category: 'Business', traffic_monthly: '2 million', submission_url: '#', topics: 'Business, finance, luxury', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: null, avg_response_days: null, article_styles: 'features, profiles, analysis', notes: null, source_tags: [], pay_structure: '$1K-$3K/article' },
  { id: 'curbed', name: 'Curbed', category: 'Lifestyle', traffic_monthly: '5 million', submission_url: '#', topics: 'Real estate, urban living, design, cities', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, analysis, guides', notes: 'Part of New York Magazine.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'eater', name: 'Eater', category: 'Food', traffic_monthly: '15 million', submission_url: '#', topics: 'Food, restaurants, dining culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, guides, reviews, analysis', notes: 'Vox Media.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'elle', name: 'ELLE', category: "Women's Topics", traffic_monthly: '10 million', submission_url: '#', topics: 'Fashion, beauty, culture, politics', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, profiles, essays, cultural criticism', notes: 'Hearst publication.', source_tags: ['tier1'], pay_structure: '$1K-$3K/article' },
  { id: 'engadget', name: 'Engadget', category: 'Technology', traffic_monthly: '20 million', submission_url: '#', topics: 'Technology, gadgets, gaming, science', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'reviews, features, news, analysis', notes: null, source_tags: ['tier2'], pay_structure: '$300-$1.5K/article' },
  { id: 'entrepreneur', name: 'Entrepreneur', category: 'Business', traffic_monthly: '15 million', submission_url: '#', topics: 'Entrepreneurship, startups, marketing, leadership', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'how-to, features, profiles, analysis', notes: null, source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'fivethirtyeight', name: 'FiveThirtyEight', category: 'All Topics', traffic_monthly: '10 million', submission_url: '#', topics: 'Data journalism, politics, sports, science', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 21, article_styles: 'data journalism, analysis, features', notes: 'Data-driven content required.', source_tags: ['tier1'], pay_structure: '$1K-$3K/article' },
  { id: 'glamour', name: 'Glamour', category: "Women's Topics", traffic_monthly: '8 million', submission_url: '#', topics: 'Fashion, beauty, culture, wellness', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 12, avg_response_days: 14, article_styles: 'features, personal essays, profiles', notes: 'Conde Nast publication.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'grub-street', name: 'Grub Street', category: 'Food', traffic_monthly: '5 million', submission_url: '#', topics: 'Food, restaurants, food culture, NYC dining', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 14, article_styles: 'features, reviews, profiles', notes: 'Part of New York Magazine.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'insider', name: 'Insider', category: 'All Topics', traffic_monthly: '100 million', submission_url: '#', topics: 'Business, tech, lifestyle, entertainment', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 20, avg_response_days: 7, article_styles: 'features, personal essays, how-to, listicles', notes: 'High volume publication.', source_tags: ['tier2'], pay_structure: '$300-$1.5K/article' },
  { id: 'inverse', name: 'Inverse', category: 'Science', traffic_monthly: '10 million', submission_url: '#', topics: 'Science, technology, entertainment, innovation', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, explainers, analysis', notes: 'Part of BDG.', source_tags: ['tier2'], pay_structure: '$300-$1K/article' },
  { id: 'jacobin', name: 'Jacobin', category: 'Politics', traffic_monthly: '2 million', submission_url: '#', topics: 'Politics, economics, labor, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'analysis, features, opinion', notes: 'Left politics focus.', source_tags: [], pay_structure: '$300-$1K/article' },
  { id: 'mashable', name: 'Mashable', category: 'Technology', traffic_monthly: '30 million', submission_url: '#', topics: 'Technology, social media, entertainment, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, reviews, analysis, listicles', notes: null, source_tags: ['tier2'], pay_structure: '$300-$1.5K/article' },
  { id: 'medium-onezero', name: 'Medium OneZero', category: 'Technology', traffic_monthly: '5 million', submission_url: '#', topics: 'Technology, science, future, digital culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, analysis, essays', notes: 'Medium publication.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'mental-floss', name: 'Mental Floss', category: 'Education', traffic_monthly: '8 million', submission_url: '#', topics: 'Science, history, language, culture, trivia', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, listicles, explainers', notes: null, source_tags: ['tier2'], pay_structure: '$300-$1K/article' },
  { id: 'money-magazine', name: 'Money Magazine', category: 'Finance', traffic_monthly: '5 million', submission_url: '#', topics: 'Personal finance, investing, retirement', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 12, avg_response_days: 14, article_styles: 'features, how-to, analysis', notes: null, source_tags: ['tier2'], pay_structure: '$500-$3K/article' },
  { id: 'new-yorker', name: 'The New Yorker', category: 'Culture', traffic_monthly: '20 million', submission_url: '#', topics: 'Culture, politics, fiction, humor, reporting', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 3000, pay_max: 15000, pay_video_min: null, pay_video_max: null, acceptance_rate: 1, avg_response_days: 60, article_styles: 'features, profiles, fiction, essays, criticism', notes: 'Most prestigious. Extremely competitive.', source_tags: ['tier1'], pay_structure: '$3K-$15K/article' },
  { id: 'nymag', name: 'New York Magazine', category: 'Culture', traffic_monthly: '25 million', submission_url: '#', topics: 'Culture, politics, fashion, food, entertainment', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 5000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, profiles, analysis, criticism', notes: null, source_tags: ['tier1'], pay_structure: '$1K-$5K/article' },
  { id: 'outside', name: 'Outside', category: 'Lifestyle', traffic_monthly: '5 million', submission_url: '#', topics: 'Outdoor adventure, fitness, travel, environment', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, adventure narratives, profiles', notes: null, source_tags: ['tier2'], pay_structure: '$500-$3K/article' },
  { id: 'pacific-standard', name: 'Pacific Standard', category: 'All Topics', traffic_monthly: '2 million', submission_url: '#', topics: 'Social justice, environment, economics, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, analysis, investigative', notes: null, source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'polygon', name: 'Polygon', category: 'Entertainment', traffic_monthly: '15 million', submission_url: '#', topics: 'Gaming, entertainment, pop culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'reviews, features, analysis, news', notes: 'Vox Media.', source_tags: ['tier2'], pay_structure: '$300-$1.5K/article' },
  { id: 'propublica', name: 'ProPublica', category: 'All Topics', traffic_monthly: '10 million', submission_url: '#', topics: 'Investigative journalism, government, business', editors: [{ name: 'Tips', email: '', role: null }], pay_min: 2000, pay_max: 10000, pay_video_min: null, pay_video_max: null, acceptance_rate: 3, avg_response_days: 30, article_styles: 'investigative, features, data journalism', notes: 'Investigative focus. Very competitive.', source_tags: ['tier1'], pay_structure: '$2K-$10K/article' },
  { id: 'quartz', name: 'Quartz', category: 'Business', traffic_monthly: '15 million', submission_url: '#', topics: 'Business, economics, technology, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 12, avg_response_days: 14, article_styles: 'analysis, features, explainers', notes: null, source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'refinery29', name: 'Refinery29', category: "Women's Topics", traffic_monthly: '15 million', submission_url: '#', topics: 'Fashion, beauty, entertainment, wellness, money', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1000, pay_video_min: null, pay_video_max: null, acceptance_rate: 20, avg_response_days: 7, article_styles: 'features, personal essays, how-to', notes: 'Part of Vice Media.', source_tags: ['tier2'], pay_structure: '$300-$1K/article' },
  { id: 'salon', name: 'Salon', category: 'All Topics', traffic_monthly: '10 million', submission_url: '#', topics: 'Politics, culture, entertainment, food', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, opinion, analysis, personal essays', notes: null, source_tags: ['tier2'], pay_structure: '$300-$1K/article' },
  { id: 'self', name: 'SELF', category: 'Health', traffic_monthly: '10 million', submission_url: '#', topics: 'Fitness, nutrition, wellness, mental health', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 12, avg_response_days: 14, article_styles: 'features, how-to, personal essays', notes: 'Conde Nast publication.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'smithsonian', name: 'Smithsonian Magazine', category: 'Science', traffic_monthly: '8 million', submission_url: '#', topics: 'Science, history, culture, innovation, nature', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 5000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 30, article_styles: 'features, profiles, investigative, photo essays', notes: 'Smithsonian Institution.', source_tags: ['tier1'], pay_structure: '$1K-$5K/article' },
  { id: 'substack', name: 'Substack (Top Newsletters)', category: 'All Topics', traffic_monthly: '50 million', submission_url: '#', topics: 'All topics via newsletter format', editors: [{ name: 'Direct', email: '', role: null }], pay_min: 100, pay_max: 5000, pay_video_min: null, pay_video_max: null, acceptance_rate: 50, avg_response_days: 7, article_styles: 'newsletters, essays, analysis', notes: 'Guest posts on top newsletters.', source_tags: [], pay_structure: '$100-$5K/guest post' },
  { id: 'techcrunch', name: 'TechCrunch', category: 'Technology', traffic_monthly: '20 million', submission_url: '#', topics: 'Startups, venture capital, technology, AI', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 14, article_styles: 'news, features, analysis, profiles', notes: null, source_tags: ['tier1'], pay_structure: '$500-$2K/article' },
  { id: 'teen-vogue', name: 'Teen Vogue', category: "Women's Topics", traffic_monthly: '8 million', submission_url: '#', topics: 'Culture, politics, fashion, identity', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, opinion, personal essays', notes: 'Conde Nast publication.', source_tags: ['tier2'], pay_structure: '$300-$1.5K/article' },
  { id: 'the-guardian', name: 'The Guardian', category: 'All Topics', traffic_monthly: '300 million', submission_url: '#', topics: 'News, politics, culture, science, environment', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 3000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 21, article_styles: 'features, opinion, analysis, investigative', notes: 'UK publication. Global reach.', source_tags: ['tier1'], pay_structure: '$500-$3K/article' },
  { id: 'the-intercept', name: 'The Intercept', category: 'Politics', traffic_monthly: '5 million', submission_url: '#', topics: 'Politics, national security, civil liberties', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 5000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 21, article_styles: 'investigative, features, analysis', notes: 'Investigative journalism focus.', source_tags: ['tier1'], pay_structure: '$1K-$5K/article' },
  { id: 'the-ringer', name: 'The Ringer', category: 'Entertainment', traffic_monthly: '10 million', submission_url: '#', topics: 'Sports, pop culture, entertainment, technology', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 12, avg_response_days: 14, article_styles: 'features, analysis, opinion, profiles', notes: 'Spotify-owned.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'vice', name: 'Vice', category: 'Culture', traffic_monthly: '30 million', submission_url: '#', topics: 'Culture, news, technology, music, food', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 12, avg_response_days: 14, article_styles: 'features, investigative, personal essays', notes: null, source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'vulture', name: 'Vulture', category: 'Entertainment', traffic_monthly: '15 million', submission_url: '#', topics: 'TV, movies, music, books, comedy', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 14, article_styles: 'features, reviews, criticism, profiles', notes: 'Part of New York Magazine.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'wealthsimple', name: 'Wealthsimple Magazine', category: 'Finance', traffic_monthly: '2 million', submission_url: '#', topics: 'Money, culture, personal finance, investing', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 1000, pay_max: 5000, pay_video_min: null, pay_video_max: null, acceptance_rate: 8, avg_response_days: 21, article_styles: 'features, personal essays, profiles', notes: 'High-quality editorial.', source_tags: ['tier1'], pay_structure: '$1K-$5K/article' },
  { id: 'wirecutter', name: 'Wirecutter (NYT)', category: 'Lifestyle', traffic_monthly: '30 million', submission_url: '#', topics: 'Product reviews, buying guides, home, tech', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 14, article_styles: 'reviews, buying guides, how-to', notes: 'NYT-owned.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'zdnet', name: 'ZDNet', category: 'Technology', traffic_monthly: '30 million', submission_url: '#', topics: 'Enterprise tech, AI, cybersecurity, cloud', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, reviews, analysis, how-to', notes: null, source_tags: ['tier2'], pay_structure: '$300-$1.5K/article' },
  { id: 'aeon', name: 'Aeon', category: 'Culture', traffic_monthly: '3 million', submission_url: '#', topics: 'Philosophy, science, society, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 5, avg_response_days: 30, article_styles: 'essays, features, analysis', notes: 'Intellectual depth required.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'atlas-obscura', name: 'Atlas Obscura', category: 'Travel', traffic_monthly: '5 million', submission_url: '#', topics: 'Hidden wonders, travel, food, history', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, guides, personal narratives', notes: 'Unique angle required.', source_tags: ['tier2'], pay_structure: '$300-$1.5K/article' },
  { id: 'catapult', name: 'Catapult', category: 'Culture', traffic_monthly: '500,000', submission_url: '#', topics: 'Personal essays, fiction, poetry, culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 1000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'personal essays, fiction, features', notes: 'Literary focus.', source_tags: [], pay_structure: '$300-$1K/article' },
  { id: 'chronicle-higher-ed', name: 'Chronicle of Higher Education', category: 'Education', traffic_monthly: '3 million', submission_url: '#', topics: 'Higher education, academia, research', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, opinion, analysis', notes: 'Academic audience.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'dwell', name: 'Dwell', category: 'Lifestyle', traffic_monthly: '3 million', submission_url: '#', topics: 'Architecture, design, modern living', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'features, profiles, design stories', notes: null, source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'electric-lit', name: 'Electric Literature', category: 'Culture', traffic_monthly: '500,000', submission_url: '#', topics: 'Literature, fiction, essays, book culture', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 300, pay_max: 800, pay_video_min: null, pay_video_max: null, acceptance_rate: 10, avg_response_days: 21, article_styles: 'essays, reviews, features', notes: 'Literary focus.', source_tags: [], pay_structure: '$300-$800/article' },
  { id: 'grid', name: 'Grid', category: 'All Topics', traffic_monthly: '2 million', submission_url: '#', topics: 'Climate, technology, policy, economics', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 12, avg_response_days: 14, article_styles: 'analysis, features, explainers', notes: null, source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
  { id: 'lithub', name: 'Literary Hub', category: 'Culture', traffic_monthly: '2 million', submission_url: '#', topics: 'Books, literature, culture, ideas', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 200, pay_max: 500, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'essays, features, reviews, excerpts', notes: null, source_tags: [], pay_structure: '$200-$500/article' },
  { id: 'marker', name: 'Marker (Medium)', category: 'Business', traffic_monthly: '3 million', submission_url: '#', topics: 'Business, economics, work, money', editors: [{ name: 'Pitches', email: '', role: null }], pay_min: 500, pay_max: 2000, pay_video_min: null, pay_video_max: null, acceptance_rate: 15, avg_response_days: 14, article_styles: 'features, analysis, profiles', notes: 'Medium publication.', source_tags: ['tier2'], pay_structure: '$500-$2K/article' },
];

// Category list derived from publications
export const CATEGORIES = Array.from(new Set(PUBLICATIONS.map(p => p.category))).sort();

// Tier classification based on acceptance rate and pay
export function getPublicationTier(pub: Publication): 'Tier 1' | 'Tier 2' | 'Tier 3' {
  const maxPay = pub.pay_max ?? 0;
  const acceptance = pub.acceptance_rate ?? 50;
  if (maxPay >= 3000 || acceptance <= 8) return 'Tier 1';
  if (maxPay >= 1000 || acceptance <= 20) return 'Tier 2';
  return 'Tier 3';
}

// Match publications to an article based on topic, category, and score
export function matchPublications(
  articleTopic: string,
  articleCategory: string,
  overallScore: number
): (Publication & { matchScore: number; tier: string })[] {
  const topicWords = articleTopic.toLowerCase().split(/\s+/);
  
  return PUBLICATIONS.map(pub => {
    let matchScore = 0;
    const pubTopics = (pub.topics + ' ' + pub.category).toLowerCase();
    
    // Topic alignment (40 points)
    const topicHits = topicWords.filter(w => w.length > 3 && pubTopics.includes(w)).length;
    matchScore += Math.min(40, topicHits * 10);
    
    // Category match (20 points)
    if (pub.category.toLowerCase() === articleCategory.toLowerCase() || pub.category === 'All Topics') {
      matchScore += 20;
    }
    
    // Score-to-tier alignment (20 points)
    const tier = getPublicationTier(pub);
    if (overallScore >= 8 && tier === 'Tier 1') matchScore += 20;
    else if (overallScore >= 6.5 && tier === 'Tier 2') matchScore += 20;
    else if (overallScore < 6.5 && tier === 'Tier 3') matchScore += 20;
    else matchScore += 10;
    
    // Pay potential (10 points)
    if ((pub.pay_max ?? 0) >= 2000) matchScore += 10;
    else if ((pub.pay_max ?? 0) >= 1000) matchScore += 5;
    
    // Acceptance rate bonus (10 points)
    if ((pub.acceptance_rate ?? 0) >= 15) matchScore += 10;
    else if ((pub.acceptance_rate ?? 0) >= 10) matchScore += 5;
    
    return { ...pub, matchScore, tier };
  })
  .sort((a, b) => b.matchScore - a.matchScore);
}
